package com.example.macpro.fbtest.model.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.macpro.fbtest.model.data.ImageUrl;

import com.example.macpro.fbtest.model.data.ImageUrlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageUrlDaoConfig;

    private final ImageUrlDao imageUrlDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageUrlDaoConfig = daoConfigMap.get(ImageUrlDao.class).clone();
        imageUrlDaoConfig.initIdentityScope(type);

        imageUrlDao = new ImageUrlDao(imageUrlDaoConfig, this);

        registerDao(ImageUrl.class, imageUrlDao);
    }
    
    public void clear() {
        imageUrlDaoConfig.clearIdentityScope();
    }

    public ImageUrlDao getImageUrlDao() {
        return imageUrlDao;
    }

}
