package com.example.macpro.fbtest.model.data;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGES".
*/
public class ImageUrlDao extends AbstractDao<ImageUrl, Void> {

    public static final String TABLENAME = "IMAGES";

    /**
     * Properties of entity ImageUrl.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ImageUrl = new Property(0, String.class, "imageUrl", false, "IMAGE_URL");
    }

    private DaoSession daoSession;


    public ImageUrlDao(DaoConfig config) {
        super(config);
    }
    
    public ImageUrlDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGES\" (" + //
                "\"IMAGE_URL\" TEXT NOT NULL UNIQUE );"); // 0: imageUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageUrl entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getImageUrl());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageUrl entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getImageUrl());
    }

    @Override
    protected final void attachEntity(ImageUrl entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ImageUrl readEntity(Cursor cursor, int offset) {
        ImageUrl entity = new ImageUrl( //
            cursor.getString(offset + 0) // imageUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageUrl entity, int offset) {
        entity.setImageUrl(cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ImageUrl entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ImageUrl entity) {
        return null;
    }

    @Override
    public boolean hasKey(ImageUrl entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
